/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 09-nov.-2018 10:24:58 a.m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

 

/* Drop Tables */

DROP TABLE IF EXISTS Banco CASCADE
;

DROP TABLE IF EXISTS Cliente CASCADE
;

DROP TABLE IF EXISTS Cuenta CASCADE
;

DROP TABLE IF EXISTS Transaccion CASCADE
;

/* Create Tables */

CREATE TABLE Banco
(
	K_BANCO varchar(10) NOT NULL,    -- Identificador del banco
	N_BANCO varchar(50) NOT NULL    -- Nombre del banco
)
;

CREATE TABLE Cliente
(
	K_IDENTIFICACION numeric(12) NOT NULL,    -- Identificaci�n del cliente
	K_TIPOID varchar(3) NOT NULL,    -- Tipo de identificaci�n del cliente (CC,CE,CRN,RG,PA)
	N_CLIENTE varchar(50) NOT NULL,    -- Nombre o raz�n social del cliente
	O_TELEFONO varchar(20) NULL,    -- Tel�fono del cliente
	O_CORREO varchar(50) NULL    -- Correo cliente 
)
;

CREATE TABLE Cuenta
(
	K_CUENTA varchar(40) NOT NULL,    -- Identificador de la cuenta bancaria
	K_IDENTIFICACION numeric(12) NOT NULL,    -- Identificaci�n del cliente a la que pertenece la cuenta
	K_TIPOID varchar(3) NOT NULL,    -- Tipo de identificaci�n del due�o de la cuenta
	K_BANCO varchar(10) NOT NULL,    -- Identificador del banco
	V_SALDO numeric(12,2) NOT NULL    -- Saldo actual de la cuenta
)
;

CREATE TABLE Transaccion 
(
	K_TRANSACCION serial NOT NULL,    -- Identificador de la transacci�n
	K_CUENTAORIGEN varchar(40) NOT NULL,    -- Identificador de la cuenta de origen
	K_CUENTADESTINO varchar(40) NOT NULL,    -- Identificador de la cuenta destino
	V_TRANSACCION numeric(12,2) NOT NULL,    -- Valor de la transacci�n 
	F_TRANSACCION date NOT NULL    -- Fecha de la transacci�n
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE Banco ADD CONSTRAINT PK_Banco
	PRIMARY KEY (K_BANCO)
;

ALTER TABLE Cliente ADD CONSTRAINT PK_CLIENTE
	PRIMARY KEY (K_IDENTIFICACION,K_TIPOID)
;

ALTER TABLE Cliente ADD CONSTRAINT CK_TIPOID CHECK (K_TIPOID IN ('CC','RC','CE','PA','CRN'))
;

ALTER TABLE Cuenta ADD CONSTRAINT PK_Cuenta
	PRIMARY KEY (K_CUENTA)
;

ALTER TABLE Cuenta ADD CONSTRAINT CK_SALDO CHECK (V_SALDO >= 0)
;

CREATE INDEX IXFK_Cuenta_Banco ON Cuenta (K_BANCO ASC)
;

CREATE INDEX IXFK_Cuenta_Cliente ON Cuenta (K_IDENTIFICACION ASC,K_TIPOID ASC)
;

ALTER TABLE Transaccion  ADD CONSTRAINT PK_Transaccion
	PRIMARY KEY (K_TRANSACCION)
;

ALTER TABLE Transaccion  ADD CONSTRAINT CK_VTRANSACCION CHECK (V_TRANSACCION > 0)
;

/* Create Foreign Key Constraints */

ALTER TABLE Cuenta ADD CONSTRAINT FK_Cuenta_Banco
	FOREIGN KEY (K_BANCO) REFERENCES Banco (K_BANCO) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Cuenta ADD CONSTRAINT FK_Cuenta_Cliente
	FOREIGN KEY (K_IDENTIFICACION,K_TIPOID) REFERENCES Cliente (K_IDENTIFICACION,K_TIPOID) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Transaccion  ADD CONSTRAINT FK_Transaccion_Cuenta_02
	FOREIGN KEY (K_CUENTADESTINO) REFERENCES Cuenta (K_CUENTA) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE Banco
	IS 'Entidad que registra informaci�n del banco'
;

COMMENT ON COLUMN Banco.K_BANCO
	IS 'Identificador del banco'
;

COMMENT ON COLUMN Banco.N_BANCO
	IS 'Nombre del banco'
;

COMMENT ON TABLE Cliente
	IS 'Entidad que almacena datos de clientes del banco'
;

COMMENT ON COLUMN Cliente.K_IDENTIFICACION
	IS 'Identificaci�n del cliente'
;

COMMENT ON COLUMN Cliente.K_TIPOID
	IS 'Tipo de identificaci�n del cliente (CC,CE,CRN,RG,PA)'
;

COMMENT ON COLUMN Cliente.N_CLIENTE
	IS 'Nombre o raz�n social del cliente'
;

COMMENT ON COLUMN Cliente.O_TELEFONO
	IS 'Tel�fono del cliente'
;

COMMENT ON COLUMN Cliente.O_CORREO
	IS 'Correo cliente '
;

COMMENT ON TABLE Cuenta
	IS 'Tabla que almacena los datos de la cuenta registrada en el banco para alguien en particular'
;

COMMENT ON COLUMN Cuenta.K_CUENTA
	IS 'Identificador de la cuenta bancaria'
;

COMMENT ON COLUMN Cuenta.K_IDENTIFICACION
	IS 'Identificaci�n del cliente a la que pertenece la cuenta'
;

COMMENT ON COLUMN Cuenta.K_TIPOID
	IS 'Tipo de identificaci�n del due�o de la cuenta'
;

COMMENT ON COLUMN Cuenta.K_BANCO
	IS 'Identificador del banco'
;

COMMENT ON COLUMN Cuenta.V_SALDO
	IS 'Saldo actual de la cuenta'
;

COMMENT ON TABLE Transaccion 
	IS 'Cada una de las transacciones del banco'
;

COMMENT ON COLUMN Transaccion.K_TRANSACCION
	IS 'Identificador de la transacci�n'
;

COMMENT ON COLUMN Transaccion.K_CUENTAORIGEN
	IS 'Identificador de la cuenta de origen'
;

COMMENT ON COLUMN Transaccion.K_CUENTADESTINO
	IS 'Identificador de la cuenta destino'
;

COMMENT ON COLUMN Transaccion.V_TRANSACCION
	IS 'Valor de la transacci�n '
;

COMMENT ON COLUMN Transaccion.F_TRANSACCION
	IS 'Fecha de la transacci�n'
;

 
