/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 15-nov.-2018 11:45:15 a.m. 				*/
/*  DBMS       : Oracle 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

begin
	EXECUTE IMMEDIATE 'DROP TABLE   Buque CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   BuqueTripulante CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   Carga CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   Cargo CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   CategoriaBuque CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   Concepto CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   CupoPaso CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   Empleado CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   EmpresaCP CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   Esclusa CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   OperadorBarco CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   OrdenDePago CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   Pago CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   Pais CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   Paso CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   Persona CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   ProgramacionDiaria CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   Puerto CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   Puja CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   Reserva CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   ReservaSubasta CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   Responsable CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   Subasta CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   TarifaCancelacion CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   TarifaPeaje CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   TarifaReserva CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   Transito CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   Tripulante CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

/* Create Tables */

CREATE TABLE  Buque
(
	K_BUQUE NUMBER(5) NOT NULL,    -- Identificador del buque inicia en 1 e incrementa consecutivamente en 1.
	K_CRN NUMBER(15) NOT NULL,    -- Número de registro de la compañía (CRN)
	K_CATEGORIA VARCHAR(3) NOT NULL,    -- Identificador categoria del buque
	N_BUQUE VARCHAR(40) NOT NULL,    -- Nombre del buque
	V_MANGA NUMBER(7,2) NOT NULL,    -- Valor manga del barco
	V_LOA NUMBER(7,2) NOT NULL,    -- Eslora del buque, largo desde la proa hasta la popa
	V_VELOCIDAD NUMBER(5,2) NULL,    -- Valor de velocidad de transito del buque en nudos
	V_PESOMUERTO NUMBER(10,2) NOT NULL    -- Número de toneladas de peso muerto (DWT)
)
;

CREATE TABLE  BuqueTripulante
(
	K_IDENTIFICACION NUMBER(12) NOT NULL,    -- Identificacion del tripulante
	K_TIPOID VARCHAR(2) NOT NULL,    -- Tipo de identificacion (CC=Cedula, RG=Registro Civil, PA=Pasaporte, CE=Cedula Exranjeria)
	K_BUQUE NUMBER(5) NOT NULL,    -- Identificacion del buque
	K_RESERVA NUMBER(10) NOT NULL    -- Identificador
)
;

CREATE TABLE  Carga
(
	K_CARGA NUMBER(12) NOT NULL,    -- Identificador de la carga
	K_RESERVA NUMBER(10) NOT NULL,    -- Identificador de la reserva
	V_PESO NUMBER(12,2) NOT NULL,    -- Valor peso total en toneladas de la carga
	I_LASTRE NUMBER(1) NOT NULL,    -- Identificador de lastre 1 = Con lastre, 0 = Sin lastre
	I_UNIDADMEDIDA VARCHAR(3) NOT NULL,    -- Identificador de la unidad de medida TON = Toneladas, DWT= Tonelada peso muerto, TM = Carga transportada, MTC = Metros cubicos, TEU = Unidad Equivalente a Veinte Pies.
	N_TIPOCARGA VARCHAR(5) NULL    -- Nombre del tipo de carga
)
;

CREATE TABLE  Cargo
(
	K_CARGO NUMBER(3) NOT NULL,
	N_CARGO VARCHAR(30) NOT NULL    -- Nombre del cargo 
)
;

CREATE TABLE  CategoriaBuque
(
	K_CATEGORIA VARCHAR(3) NOT NULL,    -- Identificador de la categoria del buque  GRA = Granelero, TAN =Tanquero, QUI= Quimiquero, GAS=Gasero, PCT= PortaContenedor, CRU= Crucero, PVH= PortaVehiculo, REF= Refrigerado, CGN= CargaGeneral, OTR= Otro,
	N_CATEGORIA VARCHAR(20) NOT NULL    -- Nombre de la categoria
)
;

CREATE TABLE  Concepto
(
	K_CONCEPTO VARCHAR(4) NOT NULL,    -- Identificador del concepto: RESV = RESERVA, CANC=CANCELACION, PEAJ = PEAJE, MULT= MULTA, OTRO = OTROS.
	N_CONCEPTO VARCHAR(30) NOT NULL    -- Nombre del concepto
)
;

CREATE TABLE  CupoPaso
(
	K_CUPOPASO NUMBER(10) NOT NULL,
	K_PASO VARCHAR(3) NOT NULL,    -- Identificador del paso por el que se transitara
	Q_CTOTALES NUMBER(2) NOT NULL,    -- Cantidad de cupos de transito totales
	Q_CDISPONIBLES NUMBER(2) NOT NULL,    -- Cantidad de cupos de transito disponibles luego de realizadas reservas
	F_ASIGNACIONCUPOS DATE NOT NULL    -- Fecha a la que corresponde el numero de cupos asignados en determinado paso
)
;

CREATE TABLE  Empleado
(
	K_IDENTIFICACION NUMBER(12) NOT NULL,    -- Numero de identificacion
	K_TIPOID VARCHAR(2) NOT NULL,    -- Tipo de identificacion (CC=Cedula, RG=Registro Civil, PA=Pasaporte, CE=Cedula Exranjeria)
	K_IDEMPRESA VARCHAR(4) NOT NULL,    -- Identificador de la empresa
	K_CARGO NUMBER(3) NOT NULL,    -- Identificador del cargo
	F_CONTRATACION DATE NOT NULL,    -- Fecha de contratacion del empleado
	O_EMAILEMPLEADO VARCHAR(40) NOT NULL,    -- Direccion de correo electronico de contacto del empleado
	O_TELEMPLEADO VARCHAR(20) NOT NULL    -- Telefono celular o fijo de contacto del empleado
)
;

CREATE TABLE  EmpresaCP
(
	K_IDEMPRESA VARCHAR(4) NOT NULL,    -- Identificador de la empresa
	N_EMPRESA VARCHAR(50) NOT NULL,    -- Nombre de la empresa
	O_TELEMPRESA VARCHAR(20) NOT NULL,    -- Telefono de contacto de la empresa
	O_DIREMPRESA VARCHAR(40) NOT NULL,    -- Direccion de contacto de la empresa
	V_KCN NUMBER(12) NOT NULL    -- Valor de identificacion de la empresa
)
;

CREATE TABLE  Esclusa
(
	K_ESCLUSA VARCHAR(4) NOT NULL,    -- Identificador de la esclusa PANX=Panamax , NEOX=Neopanamax
	N_ESCLUSA VARCHAR2(20) NOT NULL    -- Nombre de la esclusa
)
;

CREATE TABLE  OperadorBarco
(
	K_CRN NUMBER(15) NOT NULL,    -- Número de registro de la compañía (CRN)
	K_PAIS NUMBER(3) NOT NULL,    -- Identificador pais
	N_OPERADOR VARCHAR(50) NOT NULL,    -- Nombre del operador
	O_TEL VARCHAR(20) NOT NULL,    -- Direccion de telefono fijo/celular
	O_DIRECCION VARCHAR(70) NOT NULL,    -- Direccion de residencia
	O_EMAIL VARCHAR(50) NOT NULL    -- Direccion de correo electronico de contacto
)
;

CREATE TABLE  OrdenDePago
(
	K_ORDENDEPAGO NUMBER(8) NOT NULL,    -- Identificador de la roden de pago
	K_RESERVA NUMBER(10) NOT NULL,    -- Identificador de la reserva
	K_CONCEPTO VARCHAR(4) NOT NULL,    -- Identificador del concepto asociado a la orden de pago
	V_ORDENDEPAGO NUMBER(9,2) NOT NULL,    -- Valor total de la orden de pago
	F_EMISION DATE NOT NULL,    -- Fecha de emision de la orden de pago
	F_MAXPAGO DATE NOT NULL,    -- Fecha maxima de cancelacion de la orden de pago
	N_ESTADOPAGO VARCHAR(3) NOT NULL    -- Cada uno de los estados de una orden de pago  (PAG=PAGADO, NPG=NO PAGADO )
)
;

CREATE TABLE  Pago
(
	K_PAGO NUMBER(8) NOT NULL,    -- Identificador pago
	K_ORDENDEPAGO NUMBER(8) NOT NULL,    -- Identificador orden de pago 
	F_PAGO DATE NOT NULL,    -- Fecha en la que se realizo el pago
	V_PAGO NUMBER(10,2) NOT NULL,    -- Valor total pagado
	I_FORMAPAGO VARCHAR(2) NOT NULL,    -- Identificador forma de pago: EF = Efectivo, TC= Tarjeta de credito, TD = Tarjeta debito.
	O_CUENTAORIGEN VARCHAR(40) NOT NULL    -- Numero de cuenta desde la que se realiza el pago
)
;

CREATE TABLE  Pais
(
	K_PAIS NUMBER(3) NOT NULL,    -- Identificador del pais
	N_PAIS VARCHAR(30) NOT NULL    -- Nombre del pais
)
;

CREATE TABLE  Paso
(
	K_PASO VARCHAR(3) NOT NULL,    -- Identificador de la esclusa: REG= Regular, SUP=Super, NEO = Neopanamax.
	N_PASO VARCHAR(30) NOT NULL,    -- Nombre de la esclusa
	V_MAXLOA NUMBER(7,2) NOT NULL,    -- Valor de LOA en metros maximo permitido para transito por la esclusa
	V_MINLOA NUMBER(7,2) NOT NULL,    -- Valor de LOA en metros  minimo permitido para transito por la esclusa
	V_MAXMANGA NUMBER(7,2) NOT NULL,    -- Valor de manga en metros maximo permitido para transito por la esclusa
	V_MINMANGA NUMBER(7,2) NOT NULL,    -- Valor de manga minimo en metros maximo permitido para transito por la esclusa
	K_IDEMPRESA VARCHAR(4) NULL
)
;

CREATE TABLE  Persona
(
	K_IDENTIFICACION NUMBER(12) NOT NULL,    -- Numero de identificacion
	K_TIPOID VARCHAR(2) NOT NULL,    -- Tipo de identificacion (CC=Cedula, RG=Registro Civil, PA=Pasaporte, CE=Cedula Exranjeria)
	N_NOMBRE1 VARCHAR(50) NOT NULL,    -- Primer nombre
	N_NOMBRE2 VARCHAR(50) NULL,    -- Segundo nombre
	N_APELLIDO1 VARCHAR(50) NOT NULL,    -- Primer apellido
	N_APELLIDO2 VARCHAR(50) NULL,    -- Segundo apellido
	F_NACIMIENTO DATE NOT NULL,    -- Fecha de nacimiento
	K_PAIS NUMBER(3) NOT NULL    -- Identificador del pais al que pertenece la persona
)
;

CREATE TABLE  ProgramacionDiaria
(
	K_PROGRAMACION NUMBER(8) NOT NULL,    -- Identificador de la programacion
	K_PUERTOLLEGADA NUMBER NOT NULL,    -- Identificador del puerto de llegada
	K_PUERTOSALIDA NUMBER NOT NULL,    -- Identificador del puerto de salida
	F_PROGYHORALLEGADA TIMESTAMP(6) NOT NULL,    -- Programacion de fecha y hora de llegada
	F_PROGYHORASALIDA TIMESTAMP(6) NOT NULL,    -- Programacion de fecha y hora de salida
	K_IDENTIFICACION NUMBER(12) NOT NULL,    -- Identificador del empleado que realizo la programacion
	K_TIPOID VARCHAR(2) NOT NULL,    -- Tipo de identificacion (CC=Cedula, RG=Registro Civil, PA=Pasaporte, CE=Cedula Exranjeria)
	K_RESERVA NUMBER(10) NOT NULL
)
;

CREATE TABLE  Puerto
(
	K_PUERTO NUMBER(5) NOT NULL,    -- Identificador del puerto
	N_PUERTO VARCHAR(30) NOT NULL    -- Nombre del puerto
)
;

CREATE TABLE  Puja
(
	K_SUBASTA NUMBER(6) NOT NULL,    -- Identificador de la subasta a la que pertenece la puja
	K_PUJA NUMBER(6) NOT NULL,    -- Identificador de la puja
	F_PUJA TIMESTAMP(6) NOT NULL,    -- Fecha de la puja
	V_PUJA NUMBER(9,2) NOT NULL,    -- Valor de la puja
	N_ESTADOPUJA VARCHAR(3) NOT NULL,    -- Estado actual de la puja (En proceso = PCS, Perdida= PER, Ganada = GAN)
	K_IDENTIFICACION NUMBER(12) NOT NULL,    -- Identificacion del responsable
	K_TIPOID VARCHAR(2) NOT NULL    -- Tipo de identificacion (CC=Cedula, RG=Registro Civil, PA=Pasaporte, CE=Cedula Exranjeria)
)
;

CREATE TABLE  Reserva
(
	K_RESERVA NUMBER(10) NOT NULL,    -- Identificador reserva
	K_BUQUE NUMBER(5) NOT NULL,    -- Identificador del buque al que pertenece la reserva
	N_ESTADORESERVA VARCHAR(3) NOT NULL,    -- Identificador del estado de la reserva (ACE=ACEPTADO, CAN=CANCELADO, PEN=PENDIENTE)
	K_IDENTIFICACION NUMBER(12) NOT NULL,    -- Identificacion del reponsable al que pertenece la reserva
	K_TIPOID VARCHAR(2) NOT NULL,    -- Tipo de identificacion (CC=Cedula, RG=Registro Civil, PA=Pasaporte, CE=Cedula Exranjeria)
	I_TIPORESERVA VARCHAR(1) NOT NULL,    -- Tipo de la reserva (J=JIT, O=Ordinaria)
	I_DIRTRANSITO VARCHAR(1) NOT NULL,    -- Direccion de transito (N=Norte, S=Sur)
	F_RESERVA DATE NOT NULL,    -- Fecha en la que se registra una reserva
	F_TRANSITO DATE NOT NULL,    -- Fecha de la reserva del día en el que se transita
	K_ESCLUSA VARCHAR(4) NOT NULL
)
;

CREATE TABLE  ReservaSubasta
(
	K_SUBASTA NUMBER(6) NOT NULL,    -- Identificador subasta
	K_RESERVA NUMBER(10) NOT NULL    -- Identificador de la reserva
)
;

CREATE TABLE  Responsable
(
	K_IDENTIFICACION NUMBER(12) NOT NULL,    -- Identificacion del responsable
	K_TIPOID VARCHAR(2) NOT NULL,    -- Tipo de identificacion (CC=Cedula, RG=Registro Civil, PA=Pasaporte, CE=Cedula Exranjeria)
	K_CRN NUMBER(15) NOT NULL,    -- Número de registro de la compañía (CRN)
	O_TELEFONOFIJO VARCHAR(20) NOT NULL,    -- Numero de telefono fijo
	O_CELULAR VARCHAR(20) NOT NULL,    -- Numero de telefono celular
	O_EMAIL VARCHAR(50) NOT NULL    -- Drieccion de correo electronico
)
;

CREATE TABLE  Subasta
(
	K_SUBASTA NUMBER(6) NOT NULL,    -- Identificador de la subasta
	F_APERTURASUBASTA DATE NOT NULL,    -- Fecha de inicio de la subasta
	F_VENCIMIENTOSUBASTA DATE NOT NULL,    -- Fecha de finalizacion de la subasta
	F_CUPOSUBASTA DATE NOT NULL,    -- Fecha del cupo que se esta subastando
	V_PUJAINICIAL NUMBER(8,2) NOT NULL,    -- Valor inicial de puja para la subasta
	V_INCREMENTOMINIMO NUMBER(8,2) NOT NULL    -- Valor de incremento entre pujas minimo
)
;

CREATE TABLE  TarifaCancelacion
(
	K_IDEMPRESA VARCHAR(4) NOT NULL,    -- Identificacion del canal de panama
	K_TARIFACANCELACION NUMBER(5) NOT NULL,    -- Identificador de la tarifa de cancelacion
	Q_RANDIAINICIAL NUMBER(3) NULL,    -- Rango inicial en el cual se efectua la cancelacion
	Q_RANDIAFINAL NUMBER(3) NULL,    -- Rango final en el cual se efectua la cancelacion
	T_INDEMNIZACIONRESERVA NUMBER(3,2) NULL,    -- Porcentaje de la reserva que sera indemnizada
	V_FIJOINDEMNIZACION NUMBER(10,2) NULL,    -- Valor fijo de la indemnizacion
	F_INICIALVIGENTE DATE NOT NULL,    -- Fecha inicial de vigencia de la tarifa
	F_FINALVIGENTE DATE NOT NULL    -- Fecha final de vigencia de la tarifa
)
;

CREATE TABLE  TarifaPeaje
(
	K_IDEMPRESA VARCHAR(4) NOT NULL,    -- Identificacion del canal de panama
	K_TARIFAPEAJE NUMBER(5) NOT NULL,    -- Identificador de la tarifa de peaje
	Q_MEDIDAINICIAL NUMBER(7) NULL,    -- Cantidad de unidades de medida de carga inicial
	Q_MEDIDAFINAL NUMBER(7) NULL,    -- Cantidad de unidades de medida de carga final
	I_UNIDADMEDIDA VARCHAR(3) NOT NULL,    -- Identificador de la unidad de medida TON = Toneladas, DWT= Tonelada peso muerto, TM = Carga transportada, MTC = Metros cubicos, TEU = Unidad Equivalente a Veinte Pies.
	I_ENLASTRE NUMBER(1) NOT NULL,    -- Valor booleano: 1 = verdadero, 0 =Falso, para indicar si el barco esta enlastre o sin lastre.
	F_INICIALVIGENTE DATE NOT NULL,    -- Fecha inicial de vigencia de la tarifa
	F_FINALVIGENTE DATE NOT NULL,    -- Fecha final de vigencia de la tarifa
	V_TARIFAPEAJE NUMBER(10,2) NOT NULL,    -- Valor de la tarifa
	K_ESCLUSA VARCHAR(4) NOT NULL,    -- Identificador de la esclusa
	K_CATEGORIA VARCHAR(3) NOT NULL,    -- Identificador de la categoria del buque
	N_TIPOCARGA VARCHAR(5) NULL    -- Nombre del tipo de carga
)
;

CREATE TABLE  TarifaReserva
(
	K_IDEMPRESA VARCHAR(4) NOT NULL,    -- Identificacion del canal de panama
	K_TARIFARESERVA NUMBER(5) NOT NULL,    -- Identificador de la tarifa de reserva
	V_MANGAINICIAL NUMBER(7,2) NULL,    -- Valor de manga inicial
	V_MANGAFINAL NUMBER(7,2) NULL,    -- Valor de manga final
	V_LOAINICIAL NUMBER(7,2) NULL,    -- Valor de loa inicial
	V_LOAFINAL NUMBER(7,2) NULL,    -- Valor de loa final
	F_INICIALVIGENTE DATE NOT NULL,    -- Fecha inicial vigente de la tarifa de reserva 
	F_FINALVIGENTE DATE NOT NULL,    -- Fecha final vigente de la tarifa de reserva 
	V_TARIFARESERVA NUMBER(10,2) NOT NULL    -- Valor de la tarifa de reserva
)
;

CREATE TABLE  Transito
(
	K_TRANSITO NUMBER(8) NOT NULL,    -- Identificador del transito
	F_YHORALLEGADA TIMESTAMP(6) NOT NULL,    -- Fecha y hora de llegada del buque
	F_YHORASALIDA TIMESTAMP(6) NOT NULL,    -- Fecha y hora de salida del buque 
	K_ESCLUSA VARCHAR(4) NOT NULL,
	K_RESERVA NUMBER(10) NOT NULL
)
;

CREATE TABLE  Tripulante
(
	K_IDENTIFICACION NUMBER(12) NOT NULL,    -- Numero de identificacion
	K_TIPOID VARCHAR(2) NOT NULL,    -- Tipo de identificacion (CC=Cedula, RG=Registro Civil, PA=Pasaporte, CE=Cedula Exranjeria)
	N_CARGO VARCHAR(30) NOT NULL,    -- Nombre del cargo que ocupa en el buque
	O_POLIZASEGURO NUMBER(8) NOT NULL    -- Numero de poliza de seguro.
)
;

/* Create Comments, Sequences and Triggers for Autonumber Columns */

COMMENT ON TABLE  Buque IS 'Cada uno de los buques pertenecientes a un OperadorBarco.'
;

COMMENT ON COLUMN  Buque.K_BUQUE IS 'Identificador del buque inicia en 1 e incrementa consecutivamente en 1.'
;

COMMENT ON COLUMN  Buque.K_CRN IS 'Número de registro de la compañía (CRN)'
;

COMMENT ON COLUMN  Buque.K_CATEGORIA IS 'Identificador categoria del buque'
;

COMMENT ON COLUMN  Buque.N_BUQUE IS 'Nombre del buque'
;

COMMENT ON COLUMN  Buque.V_MANGA IS 'Valor manga del barco'
;

COMMENT ON COLUMN  Buque.V_LOA IS 'Eslora del buque, largo desde la proa hasta la popa'
;

COMMENT ON COLUMN  Buque.V_VELOCIDAD IS 'Valor de velocidad de transito del buque en nudos'
;

COMMENT ON COLUMN  Buque.V_PESOMUERTO IS 'Número de toneladas de peso muerto (DWT)'
;

COMMENT ON TABLE  BuqueTripulante IS 'Cada uno de los tripulantes de un buque.'
;

COMMENT ON COLUMN  BuqueTripulante.K_IDENTIFICACION IS 'Identificacion del tripulante'
;

COMMENT ON COLUMN  BuqueTripulante.K_TIPOID IS 'Tipo de identificacion (CC=Cedula, RG=Registro Civil, PA=Pasaporte, CE=Cedula Exranjeria)'
;

COMMENT ON COLUMN  BuqueTripulante.K_BUQUE IS 'Identificacion del buque'
;

COMMENT ON COLUMN  BuqueTripulante.K_RESERVA IS 'Identificador'
;

COMMENT ON TABLE  Carga IS 'Cada una de las cargas que lleva un buque en el momento de realizar el transito.'
;

COMMENT ON COLUMN  Carga.K_CARGA IS 'Identificador de la carga'
;

COMMENT ON COLUMN  Carga.K_RESERVA IS 'Identificador de la reserva'
;

COMMENT ON COLUMN  Carga.V_PESO IS 'Valor peso total en toneladas de la carga'
;

COMMENT ON COLUMN  Carga.I_LASTRE IS 'Identificador de lastre 1 = Con lastre, 0 = Sin lastre'
;

COMMENT ON COLUMN  Carga.I_UNIDADMEDIDA IS 'Identificador de la unidad de medida TON = Toneladas, DWT= Tonelada peso muerto, TM = Carga transportada, MTC = Metros cubicos, TEU = Unidad Equivalente a Veinte Pies.'
;

COMMENT ON COLUMN  Carga.N_TIPOCARGA IS 'Nombre del tipo de carga'
;

COMMENT ON TABLE  Cargo IS 'Cada uno de los cargos que desempeña un empleado en la compañia.'
;

COMMENT ON COLUMN  Cargo.N_CARGO IS 'Nombre del cargo '
;

COMMENT ON TABLE  CategoriaBuque IS 'Cada una de las categorias de los buques: Granelero, Tanquero, Quimiquero, Gasero, PortaContenedor, Crucero, PortaVehiculo, Refrigerado, CargaGeneral, Otro,'
;

COMMENT ON COLUMN  CategoriaBuque.K_CATEGORIA IS 'Identificador de la categoria del buque  GRA = Granelero, TAN =Tanquero, QUI= Quimiquero, GAS=Gasero, PCT= PortaContenedor, CRU= Crucero, PVH= PortaVehiculo, REF= Refrigerado, CGN= CargaGeneral, OTR= Otro,'
;

COMMENT ON COLUMN  CategoriaBuque.N_CATEGORIA IS 'Nombre de la categoria'
;

COMMENT ON TABLE  Concepto IS 'Cada uno de los conceptos por los cuales se genero una orden de pago RESV = RESERVA, CANC=CANCELACION, PEAJ = PEAJE, MULT= MULTA, OTRO = OTROS..'
;

COMMENT ON COLUMN  Concepto.K_CONCEPTO IS 'Identificador del concepto: RESV = RESERVA, CANC=CANCELACION, PEAJ = PEAJE, MULT= MULTA, OTRO = OTROS.'
;

COMMENT ON COLUMN  Concepto.N_CONCEPTO IS 'Nombre del concepto'
;

COMMENT ON TABLE  CupoPaso IS 'Cada uno de los cupos asignados a cada paso.'
;

COMMENT ON COLUMN  CupoPaso.K_PASO IS 'Identificador del paso por el que se transitara'
;

COMMENT ON COLUMN  CupoPaso.Q_CTOTALES IS 'Cantidad de cupos de transito totales'
;

COMMENT ON COLUMN  CupoPaso.Q_CDISPONIBLES IS 'Cantidad de cupos de transito disponibles luego de realizadas reservas'
;

COMMENT ON COLUMN  CupoPaso.F_ASIGNACIONCUPOS IS 'Fecha a la que corresponde el numero de cupos asignados en determinado paso'
;

COMMENT ON TABLE  Empleado IS 'Cada uno de los empleados asociados a la empresa del canal de panama.'
;

COMMENT ON COLUMN  Empleado.K_IDENTIFICACION IS 'Numero de identificacion'
;

COMMENT ON COLUMN  Empleado.K_TIPOID IS 'Tipo de identificacion (CC=Cedula, RG=Registro Civil, PA=Pasaporte, CE=Cedula Exranjeria)'
;

COMMENT ON COLUMN  Empleado.K_IDEMPRESA IS 'Identificador de la empresa'
;

COMMENT ON COLUMN  Empleado.K_CARGO IS 'Identificador del cargo'
;

COMMENT ON COLUMN  Empleado.F_CONTRATACION IS 'Fecha de contratacion del empleado'
;

COMMENT ON COLUMN  Empleado.O_EMAILEMPLEADO IS 'Direccion de correo electronico de contacto del empleado'
;

COMMENT ON COLUMN  Empleado.O_TELEMPLEADO IS 'Telefono celular o fijo de contacto del empleado'
;

COMMENT ON TABLE  EmpresaCP IS 'Empresa responsable del Canal de Panama.'
;

COMMENT ON COLUMN  EmpresaCP.K_IDEMPRESA IS 'Identificador de la empresa'
;

COMMENT ON COLUMN  EmpresaCP.N_EMPRESA IS 'Nombre de la empresa'
;

COMMENT ON COLUMN  EmpresaCP.O_TELEMPRESA IS 'Telefono de contacto de la empresa'
;

COMMENT ON COLUMN  EmpresaCP.O_DIREMPRESA IS 'Direccion de contacto de la empresa'
;

COMMENT ON COLUMN  EmpresaCP.V_KCN IS 'Valor de identificacion de la empresa'
;

COMMENT ON TABLE  Esclusa IS 'Esclusas del canal de Panama'
;

COMMENT ON COLUMN  Esclusa.K_ESCLUSA IS 'Identificador de la esclusa PANX=Panamax , NEOX=Neopanamax'
;

COMMENT ON COLUMN  Esclusa.N_ESCLUSA IS 'Nombre de la esclusa'
;

COMMENT ON TABLE  OperadorBarco IS 'Cada uno de los operadores que hacen uso del canal de panama.'
;

COMMENT ON COLUMN  OperadorBarco.K_CRN IS 'Número de registro de la compañía (CRN)'
;

COMMENT ON COLUMN  OperadorBarco.K_PAIS IS 'Identificador pais'
;

COMMENT ON COLUMN  OperadorBarco.N_OPERADOR IS 'Nombre del operador'
;

COMMENT ON COLUMN  OperadorBarco.O_TEL IS 'Direccion de telefono fijo/celular'
;

COMMENT ON COLUMN  OperadorBarco.O_DIRECCION IS 'Direccion de residencia'
;

COMMENT ON COLUMN  OperadorBarco.O_EMAIL IS 'Direccion de correo electronico de contacto'
;

COMMENT ON TABLE  OrdenDePago IS 'Cada una de las ordenes de pago generadas en la operacion del canal de panama.'
;

COMMENT ON COLUMN  OrdenDePago.K_ORDENDEPAGO IS 'Identificador de la roden de pago'
;

COMMENT ON COLUMN  OrdenDePago.K_RESERVA IS 'Identificador de la reserva'
;

COMMENT ON COLUMN  OrdenDePago.K_CONCEPTO IS 'Identificador del concepto asociado a la orden de pago'
;

COMMENT ON COLUMN  OrdenDePago.V_ORDENDEPAGO IS 'Valor total de la orden de pago'
;

COMMENT ON COLUMN  OrdenDePago.F_EMISION IS 'Fecha de emision de la orden de pago'
;

COMMENT ON COLUMN  OrdenDePago.F_MAXPAGO IS 'Fecha maxima de cancelacion de la orden de pago'
;

COMMENT ON COLUMN  OrdenDePago.N_ESTADOPAGO IS 'Cada uno de los estados de una orden de pago  (PAG=PAGADO, NPG=NO PAGADO )'
;

COMMENT ON TABLE  Pago IS 'Cada uno de los registros de pago asociados a una orden de pago.'
;

COMMENT ON COLUMN  Pago.K_PAGO IS 'Identificador pago'
;

COMMENT ON COLUMN  Pago.K_ORDENDEPAGO IS 'Identificador orden de pago '
;

COMMENT ON COLUMN  Pago.F_PAGO IS 'Fecha en la que se realizo el pago'
;

COMMENT ON COLUMN  Pago.V_PAGO IS 'Valor total pagado'
;

COMMENT ON COLUMN  Pago.I_FORMAPAGO IS 'Identificador forma de pago: EF = Efectivo, TC= Tarjeta de credito, TD = Tarjeta debito.'
;

COMMENT ON COLUMN  Pago.O_CUENTAORIGEN IS 'Numero de cuenta desde la que se realiza el pago'
;

COMMENT ON TABLE  Pais IS 'Cada uno de los paises del mundo.'
;

COMMENT ON COLUMN  Pais.K_PAIS IS 'Identificador del pais'
;

COMMENT ON COLUMN  Pais.N_PAIS IS 'Nombre del pais'
;

COMMENT ON TABLE  Paso IS 'Cada uno de los pasos asociados a una reserva por el que realizara transito un buque'
;

COMMENT ON COLUMN  Paso.K_PASO IS 'Identificador de la esclusa: REG= Regular, SUP=Super, NEO = Neopanamax.'
;

COMMENT ON COLUMN  Paso.N_PASO IS 'Nombre de la esclusa'
;

COMMENT ON COLUMN  Paso.V_MAXLOA IS 'Valor de LOA en metros maximo permitido para transito por la esclusa'
;

COMMENT ON COLUMN  Paso.V_MINLOA IS 'Valor de LOA en metros  minimo permitido para transito por la esclusa'
;

COMMENT ON COLUMN  Paso.V_MAXMANGA IS 'Valor de manga en metros maximo permitido para transito por la esclusa'
;

COMMENT ON COLUMN  Paso.V_MINMANGA IS 'Valor de manga minimo en metros maximo permitido para transito por la esclusa'
;

COMMENT ON TABLE  Persona IS 'Cada una de las personas registradas en el sistema.'
;

COMMENT ON COLUMN  Persona.K_IDENTIFICACION IS 'Numero de identificacion'
;

COMMENT ON COLUMN  Persona.K_TIPOID IS 'Tipo de identificacion (CC=Cedula, RG=Registro Civil, PA=Pasaporte, CE=Cedula Exranjeria)'
;

COMMENT ON COLUMN  Persona.N_NOMBRE1 IS 'Primer nombre'
;

COMMENT ON COLUMN  Persona.N_NOMBRE2 IS 'Segundo nombre'
;

COMMENT ON COLUMN  Persona.N_APELLIDO1 IS 'Primer apellido'
;

COMMENT ON COLUMN  Persona.N_APELLIDO2 IS 'Segundo apellido'
;

COMMENT ON COLUMN  Persona.F_NACIMIENTO IS 'Fecha de nacimiento'
;

COMMENT ON COLUMN  Persona.K_PAIS IS 'Identificador del pais al que pertenece la persona'
;

COMMENT ON TABLE  ProgramacionDiaria IS 'Registro del numero de buques que van a transitar efectivamente cad dia.'
;

COMMENT ON COLUMN  ProgramacionDiaria.K_PROGRAMACION IS 'Identificador de la programacion'
;

COMMENT ON COLUMN  ProgramacionDiaria.K_PUERTOLLEGADA IS 'Identificador del puerto de llegada'
;

COMMENT ON COLUMN  ProgramacionDiaria.K_PUERTOSALIDA IS 'Identificador del puerto de salida'
;

COMMENT ON COLUMN  ProgramacionDiaria.F_PROGYHORALLEGADA IS 'Programacion de fecha y hora de llegada'
;

COMMENT ON COLUMN  ProgramacionDiaria.F_PROGYHORASALIDA IS 'Programacion de fecha y hora de salida'
;

COMMENT ON COLUMN  ProgramacionDiaria.K_IDENTIFICACION IS 'Identificador del empleado que realizo la programacion'
;

COMMENT ON COLUMN  ProgramacionDiaria.K_TIPOID IS 'Tipo de identificacion (CC=Cedula, RG=Registro Civil, PA=Pasaporte, CE=Cedula Exranjeria)'
;

COMMENT ON TABLE  Puerto IS 'Cada uno de los puertos asociados al canal de panama.'
;

COMMENT ON COLUMN  Puerto.K_PUERTO IS 'Identificador del puerto'
;

COMMENT ON COLUMN  Puerto.N_PUERTO IS 'Nombre del puerto'
;

COMMENT ON TABLE  Puja IS 'Cada una de las pujas asociadas a una subasta.'
;

COMMENT ON COLUMN  Puja.K_SUBASTA IS 'Identificador de la subasta a la que pertenece la puja'
;

COMMENT ON COLUMN  Puja.K_PUJA IS 'Identificador de la puja'
;

COMMENT ON COLUMN  Puja.F_PUJA IS 'Fecha de la puja'
;

COMMENT ON COLUMN  Puja.V_PUJA IS 'Valor de la puja'
;

COMMENT ON COLUMN  Puja.N_ESTADOPUJA IS 'Estado actual de la puja (En proceso = PCS, Perdida= PER, Ganada = GAN)'
;

COMMENT ON COLUMN  Puja.K_IDENTIFICACION IS 'Identificacion del responsable'
;

COMMENT ON COLUMN  Puja.K_TIPOID IS 'Tipo de identificacion (CC=Cedula, RG=Registro Civil, PA=Pasaporte, CE=Cedula Exranjeria)'
;

COMMENT ON TABLE  Reserva IS 'Cada una de las reservas realizadas por un operador de barco.'
;

COMMENT ON COLUMN  Reserva.K_RESERVA IS 'Identificador reserva'
;

COMMENT ON COLUMN  Reserva.K_BUQUE IS 'Identificador del buque al que pertenece la reserva'
;

COMMENT ON COLUMN  Reserva.N_ESTADORESERVA IS 'Identificador del estado de la reserva (ACE=ACEPTADO, CAN=CANCELADO, PEN=PENDIENTE)'
;

COMMENT ON COLUMN  Reserva.K_IDENTIFICACION IS 'Identificacion del reponsable al que pertenece la reserva'
;

COMMENT ON COLUMN  Reserva.K_TIPOID IS 'Tipo de identificacion (CC=Cedula, RG=Registro Civil, PA=Pasaporte, CE=Cedula Exranjeria)'
;

COMMENT ON COLUMN  Reserva.I_TIPORESERVA IS 'Tipo de la reserva (J=JIT, O=Ordinaria)'
;

COMMENT ON COLUMN  Reserva.I_DIRTRANSITO IS 'Direccion de transito (N=Norte, S=Sur)'
;

COMMENT ON COLUMN  Reserva.F_RESERVA IS 'Fecha en la que se registra una reserva'
;

COMMENT ON COLUMN  Reserva.F_TRANSITO IS 'Fecha de la reserva del día en el que se transita'
;

COMMENT ON TABLE  ReservaSubasta IS 'Cada una reservas que se ofrecen en modalidad de subasta.'
;

COMMENT ON COLUMN  ReservaSubasta.K_SUBASTA IS 'Identificador subasta'
;

COMMENT ON COLUMN  ReservaSubasta.K_RESERVA IS 'Identificador de la reserva'
;

COMMENT ON TABLE  Responsable IS 'Cada uno de los responsables de hacer una reserva delegador por un operador de barco.'
;

COMMENT ON COLUMN  Responsable.K_IDENTIFICACION IS 'Identificacion del responsable'
;

COMMENT ON COLUMN  Responsable.K_TIPOID IS 'Tipo de identificacion (CC=Cedula, RG=Registro Civil, PA=Pasaporte, CE=Cedula Exranjeria)'
;

COMMENT ON COLUMN  Responsable.K_CRN IS 'Número de registro de la compañía (CRN)'
;

COMMENT ON COLUMN  Responsable.O_TELEFONOFIJO IS 'Numero de telefono fijo'
;

COMMENT ON COLUMN  Responsable.O_CELULAR IS 'Numero de telefono celular'
;

COMMENT ON COLUMN  Responsable.O_EMAIL IS 'Drieccion de correo electronico'
;

COMMENT ON TABLE  Subasta IS 'Cada una de las subastas ofertadas.'
;

COMMENT ON COLUMN  Subasta.K_SUBASTA IS 'Identificador de la subasta'
;

COMMENT ON COLUMN  Subasta.F_APERTURASUBASTA IS 'Fecha de inicio de la subasta'
;

COMMENT ON COLUMN  Subasta.F_VENCIMIENTOSUBASTA IS 'Fecha de finalizacion de la subasta'
;

COMMENT ON COLUMN  Subasta.F_CUPOSUBASTA IS 'Fecha del cupo que se esta subastando'
;

COMMENT ON COLUMN  Subasta.V_PUJAINICIAL IS 'Valor inicial de puja para la subasta'
;

COMMENT ON COLUMN  Subasta.V_INCREMENTOMINIMO IS 'Valor de incremento entre pujas minimo'
;

COMMENT ON TABLE  TarifaCancelacion IS 'Cada una de las tarifas de cancelacion parametrizadas por la autoridad del canal de panama.'
;

COMMENT ON COLUMN  TarifaCancelacion.K_IDEMPRESA IS 'Identificacion del canal de panama'
;

COMMENT ON COLUMN  TarifaCancelacion.K_TARIFACANCELACION IS 'Identificador de la tarifa de cancelacion'
;

COMMENT ON COLUMN  TarifaCancelacion.Q_RANDIAINICIAL IS 'Rango inicial en el cual se efectua la cancelacion'
;

COMMENT ON COLUMN  TarifaCancelacion.Q_RANDIAFINAL IS 'Rango final en el cual se efectua la cancelacion'
;

COMMENT ON COLUMN  TarifaCancelacion.T_INDEMNIZACIONRESERVA IS 'Porcentaje de la reserva que sera indemnizada'
;

COMMENT ON COLUMN  TarifaCancelacion.V_FIJOINDEMNIZACION IS 'Valor fijo de la indemnizacion'
;

COMMENT ON COLUMN  TarifaCancelacion.F_INICIALVIGENTE IS 'Fecha inicial de vigencia de la tarifa'
;

COMMENT ON COLUMN  TarifaCancelacion.F_FINALVIGENTE IS 'Fecha final de vigencia de la tarifa'
;

COMMENT ON TABLE  TarifaPeaje IS 'Cada una de las tarifas de peaje parametrizadas por la autoridad del canal de panama.'
;

COMMENT ON COLUMN  TarifaPeaje.K_IDEMPRESA IS 'Identificacion del canal de panama'
;

COMMENT ON COLUMN  TarifaPeaje.K_TARIFAPEAJE IS 'Identificador de la tarifa de peaje'
;

COMMENT ON COLUMN  TarifaPeaje.Q_MEDIDAINICIAL IS 'Cantidad de unidades de medida de carga inicial'
;

COMMENT ON COLUMN  TarifaPeaje.Q_MEDIDAFINAL IS 'Cantidad de unidades de medida de carga final'
;

COMMENT ON COLUMN  TarifaPeaje.I_UNIDADMEDIDA IS 'Identificador de la unidad de medida TON = Toneladas, DWT= Tonelada peso muerto, TM = Carga transportada, MTC = Metros cubicos, TEU = Unidad Equivalente a Veinte Pies.'
;

COMMENT ON COLUMN  TarifaPeaje.I_ENLASTRE IS 'Valor booleano: 1 = verdadero, 0 =Falso, para indicar si el barco esta enlastre o sin lastre.'
;

COMMENT ON COLUMN  TarifaPeaje.F_INICIALVIGENTE IS 'Fecha inicial de vigencia de la tarifa'
;

COMMENT ON COLUMN  TarifaPeaje.F_FINALVIGENTE IS 'Fecha final de vigencia de la tarifa'
;

COMMENT ON COLUMN  TarifaPeaje.V_TARIFAPEAJE IS 'Valor de la tarifa'
;

COMMENT ON COLUMN  TarifaPeaje.K_ESCLUSA IS 'Identificador de la esclusa'
;

COMMENT ON COLUMN  TarifaPeaje.K_CATEGORIA IS 'Identificador de la categoria del buque'
;

COMMENT ON COLUMN  TarifaPeaje.N_TIPOCARGA IS 'Nombre del tipo de carga'
;

COMMENT ON TABLE  TarifaReserva IS 'Cada una de las tarifas de reserva parametrizadas por la autoridad del canal de panama.'
;

COMMENT ON COLUMN  TarifaReserva.K_IDEMPRESA IS 'Identificacion del canal de panama'
;

COMMENT ON COLUMN  TarifaReserva.K_TARIFARESERVA IS 'Identificador de la tarifa de reserva'
;

COMMENT ON COLUMN  TarifaReserva.V_MANGAINICIAL IS 'Valor de manga inicial'
;

COMMENT ON COLUMN  TarifaReserva.V_MANGAFINAL IS 'Valor de manga final'
;

COMMENT ON COLUMN  TarifaReserva.V_LOAINICIAL IS 'Valor de loa inicial'
;

COMMENT ON COLUMN  TarifaReserva.V_LOAFINAL IS 'Valor de loa final'
;

COMMENT ON COLUMN  TarifaReserva.F_INICIALVIGENTE IS 'Fecha inicial vigente de la tarifa de reserva '
;

COMMENT ON COLUMN  TarifaReserva.F_FINALVIGENTE IS 'Fecha final vigente de la tarifa de reserva '
;

COMMENT ON COLUMN  TarifaReserva.V_TARIFARESERVA IS 'Valor de la tarifa de reserva'
;

COMMENT ON TABLE  Transito IS 'Cada uno de los registros que transitan por el canal de panama.'
;

COMMENT ON COLUMN  Transito.K_TRANSITO IS 'Identificador del transito'
;

COMMENT ON COLUMN  Transito.F_YHORALLEGADA IS 'Fecha y hora de llegada del buque'
;

COMMENT ON COLUMN  Transito.F_YHORASALIDA IS 'Fecha y hora de salida del buque '
;

COMMENT ON TABLE  Tripulante IS 'Cada uno de los tripulantes registrados en el sistema.'
;

COMMENT ON COLUMN  Tripulante.K_IDENTIFICACION IS 'Numero de identificacion'
;

COMMENT ON COLUMN  Tripulante.K_TIPOID IS 'Tipo de identificacion (CC=Cedula, RG=Registro Civil, PA=Pasaporte, CE=Cedula Exranjeria)'
;

COMMENT ON COLUMN  Tripulante.N_CARGO IS 'Nombre del cargo que ocupa en el buque'
;

COMMENT ON COLUMN  Tripulante.O_POLIZASEGURO IS 'Numero de poliza de seguro.'
;

/* Create Primary Keys, Indexes, Uniques, Checks, Triggers */

ALTER TABLE  Buque 
 ADD CONSTRAINT PK_BUQUE
	PRIMARY KEY (K_BUQUE) 
 USING INDEX
;

ALTER TABLE  Buque 
 ADD CONSTRAINT CK_BUQUE CHECK (K_BUQUE > 0)
;

ALTER TABLE  Buque 
 ADD CONSTRAINT CK_MANGA CHECK (V_MANGA > 0)
;

ALTER TABLE  Buque 
 ADD CONSTRAINT CK_LOA CHECK (V_LOA > 0)
;

ALTER TABLE  Buque 
 ADD CONSTRAINT CK_VELOCIDAD CHECK (V_VELOCIDAD > 0)
;

ALTER TABLE  Buque 
 ADD CONSTRAINT CK_PESOMUERTO CHECK (V_PESOMUERTO > 0)
;

ALTER TABLE  BuqueTripulante 
 ADD CONSTRAINT PK_BuqueTripulante
	PRIMARY KEY (K_BUQUE,K_IDENTIFICACION,K_TIPOID) 
 USING INDEX
;

ALTER TABLE  Carga 
 ADD CONSTRAINT PK_Carga
	PRIMARY KEY (K_CARGA) 
 USING INDEX
;

ALTER TABLE  Carga 
 ADD CONSTRAINT CK_CARGA CHECK (K_CARGA > 0)
;

ALTER TABLE  Carga 
 ADD CONSTRAINT CK_PESO CHECK (V_PESO > 0)
;

ALTER TABLE  Carga 
 ADD CONSTRAINT CK_LASTRE CHECK (I_LASTRE = 0 OR I_LASTRE = 1)
;

ALTER TABLE  Carga 
 ADD CONSTRAINT CK_UNIDADESDEMEDIDA CHECK (I_UNIDADMEDIDA IN ('TON','DWT','TM','MTC','TEU'))
;

ALTER TABLE  Cargo 
 ADD CONSTRAINT PK_CARGO
	PRIMARY KEY (K_CARGO) 
 USING INDEX
;

ALTER TABLE  Cargo 
 ADD CONSTRAINT CK_CARGO CHECK (K_CARGO > 0)
;

ALTER TABLE  CategoriaBuque 
 ADD CONSTRAINT PK_CATEGORIABUQUE
	PRIMARY KEY (K_CATEGORIA) 
 USING INDEX
;

ALTER TABLE  CategoriaBuque 
 ADD CONSTRAINT CK_CATEGORIA CHECK (K_CATEGORIA IN ('GRA','TAN','QUI','GAS', 'PCT', 'CRU', 'PVH', 'REF', 'CGN', 'OTR' ))
;

ALTER TABLE  Concepto 
 ADD CONSTRAINT PK_Concepto
	PRIMARY KEY (K_CONCEPTO) 
 USING INDEX
;

ALTER TABLE  Concepto 
 ADD CONSTRAINT CK_CONCEPTO CHECK (K_CONCEPTO IN ('RESV','CANC','PEAJ','MULT', 'OTRO'))
;

ALTER TABLE  CupoPaso 
 ADD CONSTRAINT PK_CupoEsclusa
	PRIMARY KEY (K_PASO,K_CUPOPASO) 
 USING INDEX
;

ALTER TABLE  CupoPaso 
 ADD CONSTRAINT CK_CTOTALES CHECK (Q_CTOTALES >= 0)
;

ALTER TABLE  CupoPaso 
 ADD CONSTRAINT CK_CDISPONIBLES CHECK (Q_CDISPONIBLES >= 0)
;

ALTER TABLE  Empleado 
 ADD CONSTRAINT PK_Empleado
	PRIMARY KEY (K_IDENTIFICACION,K_TIPOID) 
 USING INDEX
;

ALTER TABLE  Empleado 
 ADD CONSTRAINT CK_EMAILEMPLEADO CHECK (O_EMAILEMPLEADO LIKE '%_@%_._%')
;

ALTER TABLE  Empleado 
 ADD CONSTRAINT CK_TELEMPLEADO CHECK (O_TELEMPLEADO LIKE '+%')
;

ALTER TABLE  EmpresaCP 
 ADD CONSTRAINT PK_EMPRESACP
	PRIMARY KEY (K_IDEMPRESA) 
 USING INDEX
;

ALTER TABLE  EmpresaCP 
 ADD CONSTRAINT CK_TELEMPRESA CHECK (O_TELEMPRESA LIKE '+%')
;

ALTER TABLE  Esclusa 
 ADD CONSTRAINT PK_Esclusa
	PRIMARY KEY (K_ESCLUSA) 
 USING INDEX
;

ALTER TABLE  Esclusa 
 ADD CONSTRAINT CK_KESCLUSA CHECK (K_ESCLUSA IN ('PANX','NEOX'))
;

ALTER TABLE  OperadorBarco 
 ADD CONSTRAINT PK_OPERADORBARCO
	PRIMARY KEY (K_CRN) 
 USING INDEX
;

ALTER TABLE  OperadorBarco 
 ADD CONSTRAINT CK_CRN CHECK (K_CRN > 0)
;

ALTER TABLE  OperadorBarco 
 ADD CONSTRAINT CK_EMAIL CHECK (O_EMAIL LIKE '%_@%_._%')
;

ALTER TABLE  OperadorBarco 
 ADD CONSTRAINT CK_TEL CHECK (O_TEL LIKE '+%')
;

ALTER TABLE  OrdenDePago 
 ADD CONSTRAINT PK_ORDENDEPAGO
	PRIMARY KEY (K_ORDENDEPAGO) 
 USING INDEX
;

ALTER TABLE  OrdenDePago 
 ADD CONSTRAINT CK_VALORORDENPAGO CHECK (V_ORDENDEPAGO > 0)
;

ALTER TABLE  OrdenDePago 
 ADD CONSTRAINT CK_MAXPAGO CHECK (F_MAXPAGO >= F_EMISION)
;

ALTER TABLE  OrdenDePago 
 ADD CONSTRAINT CK_NESTADOPAGO CHECK (N_ESTADOPAGO IN ('NPG', 'PAG'))
;

ALTER TABLE  Pago 
 ADD CONSTRAINT PK_Pago
	PRIMARY KEY (K_PAGO,K_ORDENDEPAGO) 
 USING INDEX
;

ALTER TABLE  Pago 
 ADD CONSTRAINT CK_FORMAPAGO CHECK (I_FORMAPAGO IN ('EF','TC','TD'))
;

ALTER TABLE  Pais 
 ADD CONSTRAINT PK_PAIS
	PRIMARY KEY (K_PAIS) 
 USING INDEX
;

ALTER TABLE  Pais 
 ADD CONSTRAINT CK_PAIS CHECK (K_PAIS > 0)
;

ALTER TABLE  Paso 
 ADD CONSTRAINT PK_PASO
	PRIMARY KEY (K_PASO) 
 USING INDEX
;

ALTER TABLE  Paso 
 ADD CONSTRAINT CK_PASO CHECK (K_PASO IN ('REG','SUP','NEO'))
;

ALTER TABLE  Paso 
 ADD CONSTRAINT CK_MAXLOA CHECK (V_MAXLOA > 0)
;

ALTER TABLE  Paso 
 ADD CONSTRAINT CK_MAXMANGA CHECK (V_MAXMANGA > 0)
;

ALTER TABLE  Paso 
 ADD CONSTRAINT CK_MINLOA CHECK (V_MINLOA > 0 )
;

ALTER TABLE  Paso 
 ADD CONSTRAINT CK_MINMANGA CHECK (V_MINMANGA > 0)
;

ALTER TABLE  Persona 
 ADD CONSTRAINT PK_PERSONA
	PRIMARY KEY (K_IDENTIFICACION,K_TIPOID) 
 USING INDEX
;

ALTER TABLE  Persona 
 ADD CONSTRAINT CK_TIPOID CHECK (K_TIPOID IN ('CC','RC','CE','PA'))
;

ALTER TABLE  Persona 
 ADD CONSTRAINT CK_IDENTIFICACION CHECK (K_IDENTIFICACION > 0)
;

ALTER TABLE  ProgramacionDiaria 
 ADD CONSTRAINT PK_PROGRAMACIONDDIARIA
	PRIMARY KEY (K_PROGRAMACION) 
 USING INDEX
;

ALTER TABLE  ProgramacionDiaria 
 ADD CONSTRAINT CK_PROGRAMACION CHECK (K_PROGRAMACION > 0)
;

ALTER TABLE  Puerto 
 ADD CONSTRAINT PK_PUERTO
	PRIMARY KEY (K_PUERTO) 
 USING INDEX
;

ALTER TABLE  Puerto 
 ADD CONSTRAINT CK_PUERTO CHECK (K_PUERTO > 0)
;

ALTER TABLE  Puja 
 ADD CONSTRAINT PK_PUJA
	PRIMARY KEY (K_PUJA) 
 USING INDEX
;

ALTER TABLE  Puja 
 ADD CONSTRAINT CK_PUJA CHECK (V_PUJA > 0)
;

ALTER TABLE  Puja 
 ADD CONSTRAINT CK_IDPUJA CHECK (K_PUJA > 0 )
;

ALTER TABLE  Puja 
 ADD CONSTRAINT CK_NESTADOPUJA CHECK (N_ESTADOPUJA IN ('PCS', 'PER', 'GAN'))
;

CREATE INDEX IXFK_Puja_Responsable   
 ON  Puja (K_IDENTIFICACION,K_TIPOID) 
;

ALTER TABLE  Reserva 
 ADD CONSTRAINT PK_RESERVA
	PRIMARY KEY (K_RESERVA) 
 USING INDEX
;

ALTER TABLE  Reserva 
 ADD CONSTRAINT CK_ITIPORESERVA CHECK (I_TIPORESERVA IN ('J', 'O'))
;

ALTER TABLE  Reserva 
 ADD CONSTRAINT CK_IDIRTRANSITO CHECK (I_DIRTRANSITO IN ('N', 'S'))
;

ALTER TABLE  Reserva 
 ADD CONSTRAINT CK_NESTADORESERVA CHECK (N_ESTADORESERVA IN ('ACE', 'CAN', 'PEN'))
;

ALTER TABLE  Reserva 
 ADD CONSTRAINT CK_RESERVA CHECK (K_RESERVA > 0 )
;

ALTER TABLE  Reserva 
 ADD CONSTRAINT CK_FECHARESERVA CHECK (F_RESERVA < F_TRANSITO)
;

ALTER TABLE  ReservaSubasta 
 ADD CONSTRAINT PK_ReservaSubasta
	PRIMARY KEY (K_RESERVA,K_SUBASTA) 
 USING INDEX
;

ALTER TABLE  Responsable 
 ADD CONSTRAINT PK_Responsable
	PRIMARY KEY (K_IDENTIFICACION,K_TIPOID) 
 USING INDEX
;

ALTER TABLE  Responsable 
 ADD CONSTRAINT CK_RESPEMAIL CHECK (O_EMAIL LIKE '%_@%_._%')
;

ALTER TABLE  Responsable 
 ADD CONSTRAINT CK_CELULAR CHECK (O_CELULAR LIKE '+%')
;

ALTER TABLE  Subasta 
 ADD CONSTRAINT PK_SUBASTA
	PRIMARY KEY (K_SUBASTA) 
 USING INDEX
;

ALTER TABLE  Subasta 
 ADD CONSTRAINT CK_SUBASTA CHECK (K_SUBASTA > 0)
;

ALTER TABLE  Subasta 
 ADD CONSTRAINT CK_PUJAINICIAL CHECK (V_PUJAINICIAL > 0)
;

ALTER TABLE  Subasta 
 ADD CONSTRAINT CK_INCREMENTOMINIMO CHECK (V_INCREMENTOMINIMO > 0)
;

ALTER TABLE  TarifaCancelacion 
 ADD CONSTRAINT PK_TarifaCancelacion
	PRIMARY KEY (K_TARIFACANCELACION,K_IDEMPRESA) 
 USING INDEX
;

ALTER TABLE  TarifaCancelacion 
 ADD CONSTRAINT CK_INDEMNIZACIONRESERVA CHECK (T_INDEMNIZACIONRESERVA >= 0 AND T_INDEMNIZACIONRESERVA <= 1.00)
;

ALTER TABLE  TarifaCancelacion 
 ADD CONSTRAINT CK_VFIJOINDEMNIZACION CHECK (V_FIJOINDEMNIZACION > 0)
;

ALTER TABLE  TarifaCancelacion 
 ADD CONSTRAINT CK_RANDIAINICIAL CHECK (Q_RANDIAINICIAL > 0)
;

ALTER TABLE  TarifaCancelacion 
 ADD CONSTRAINT CK_RANDIAFINAL CHECK (Q_RANDIAFINAL > 0)
;

ALTER TABLE  TarifaCancelacion 
 ADD CONSTRAINT CK_TARIFACANCELACION CHECK (K_TARIFACANCELACION > 0)
;

ALTER TABLE  TarifaCancelacion 
 ADD CONSTRAINT CK_CFINALVIGENTE CHECK (F_FINALVIGENTE >= F_INICIALVIGENTE)
;

ALTER TABLE  TarifaPeaje 
 ADD CONSTRAINT PK_TarifaPeaje
	PRIMARY KEY (K_TARIFAPEAJE,K_IDEMPRESA) 
 USING INDEX
;

ALTER TABLE  TarifaPeaje 
 ADD CONSTRAINT CK_IDTARIFAPEAJE CHECK (K_TARIFAPEAJE > 0)
;

ALTER TABLE  TarifaPeaje 
 ADD CONSTRAINT CK_UNIDADMEDIDA CHECK (I_UNIDADMEDIDA IN ('TON','DWT','TM','MTC','TEU'))
;

ALTER TABLE  TarifaPeaje 
 ADD CONSTRAINT CK_ENLASTRE CHECK (I_ENLASTRE = 0 OR I_ENLASTRE = 1)
;

ALTER TABLE  TarifaPeaje 
 ADD CONSTRAINT CK_TARIFAPEAJE CHECK (V_TARIFAPEAJE > 0)
;

ALTER TABLE  TarifaPeaje 
 ADD CONSTRAINT CK_FINALVIGENTE CHECK (F_FINALVIGENTE >= F_INICIALVIGENTE)
;

ALTER TABLE  TarifaReserva 
 ADD CONSTRAINT PK_TarifaReserva
	PRIMARY KEY (K_TARIFARESERVA,K_IDEMPRESA) 
 USING INDEX
;

ALTER TABLE  TarifaReserva 
 ADD CONSTRAINT CK_TARIFARESERVA CHECK (V_TARIFARESERVA > 0)
;

ALTER TABLE  TarifaReserva 
 ADD CONSTRAINT CK_IDTARIFARESERVA CHECK (K_TARIFARESERVA > 0)
;

ALTER TABLE  TarifaReserva 
 ADD CONSTRAINT CK_MANGAINICIAL CHECK (V_MANGAINICIAL > 0)
;

ALTER TABLE  TarifaReserva 
 ADD CONSTRAINT CK_MANGAFINAL CHECK (V_MANGAFINAL > 0)
;

ALTER TABLE  TarifaReserva 
 ADD CONSTRAINT CK_LOAINICIAL CHECK (V_LOAFINAL > 0)
;

ALTER TABLE  TarifaReserva 
 ADD CONSTRAINT CK_LOAFINAL CHECK (V_LOAFINAL > 0)
;

ALTER TABLE  TarifaReserva 
 ADD CONSTRAINT CK_FFINALVIGENTE CHECK (F_FINALVIGENTE >= F_INICIALVIGENTE)
;

ALTER TABLE  Transito 
 ADD CONSTRAINT PK_TRANSITO
	PRIMARY KEY (K_TRANSITO) 
 USING INDEX
;

ALTER TABLE  Transito 
 ADD CONSTRAINT CK_TRANSITO CHECK (K_TRANSITO > 0)
;

ALTER TABLE  Tripulante 
 ADD CONSTRAINT PK_Tripulante
	PRIMARY KEY (K_IDENTIFICACION,K_TIPOID) 
 USING INDEX
;

ALTER TABLE  Tripulante 
 ADD CONSTRAINT CK_POLIZASEGURO CHECK (O_POLIZASEGURO > 0)
;

/* Create Foreign Key Constraints */

ALTER TABLE  Buque 
 ADD CONSTRAINT FK_Buque_CategoriaBuque
	FOREIGN KEY (K_CATEGORIA) REFERENCES  CategoriaBuque (K_CATEGORIA)
;

ALTER TABLE  Buque 
 ADD CONSTRAINT FK_BUQUE_OPERADORBARCO
	FOREIGN KEY (K_CRN) REFERENCES  OperadorBarco (K_CRN)
;

ALTER TABLE  BuqueTripulante 
 ADD CONSTRAINT FK_BuqueTripulante_Buque
	FOREIGN KEY (K_BUQUE) REFERENCES  Buque (K_BUQUE)
;

ALTER TABLE  BuqueTripulante 
 ADD CONSTRAINT FK_BuqueTripulante_Reserva
	FOREIGN KEY (K_RESERVA) REFERENCES  Reserva (K_RESERVA)
;

ALTER TABLE  BuqueTripulante 
 ADD CONSTRAINT FK_BuqueTripulante_Tripulante
	FOREIGN KEY (K_IDENTIFICACION,K_TIPOID) REFERENCES  Tripulante (K_IDENTIFICACION,K_TIPOID)
;

ALTER TABLE  Carga 
 ADD CONSTRAINT FK_Carga_Reserva
	FOREIGN KEY (K_RESERVA) REFERENCES  Reserva (K_RESERVA)
;

ALTER TABLE  CupoPaso 
 ADD CONSTRAINT FK_CUPOESCLUSA_PASO
	FOREIGN KEY (K_PASO) REFERENCES  Paso (K_PASO)
;

ALTER TABLE  Empleado 
 ADD CONSTRAINT FK_Empleado_Cargo
	FOREIGN KEY (K_CARGO) REFERENCES  Cargo (K_CARGO)
;

ALTER TABLE  Empleado 
 ADD CONSTRAINT FK_Empleado_EmpresaCP
	FOREIGN KEY (K_IDEMPRESA) REFERENCES  EmpresaCP (K_IDEMPRESA)
;

ALTER TABLE  Empleado 
 ADD CONSTRAINT FK_Empleado_Persona
	FOREIGN KEY (K_IDENTIFICACION,K_TIPOID) REFERENCES  Persona (K_IDENTIFICACION,K_TIPOID)
;

ALTER TABLE  OperadorBarco 
 ADD CONSTRAINT FK_Operador_Pais
	FOREIGN KEY (K_PAIS) REFERENCES  Pais (K_PAIS)
;

ALTER TABLE  OrdenDePago 
 ADD CONSTRAINT FK_OrdenDePago_Concepto
	FOREIGN KEY (K_CONCEPTO) REFERENCES  Concepto (K_CONCEPTO)
;

ALTER TABLE  OrdenDePago 
 ADD CONSTRAINT FK_OrdenDePago_Reserva
	FOREIGN KEY (K_RESERVA) REFERENCES  Reserva (K_RESERVA)
;

ALTER TABLE  Pago 
 ADD CONSTRAINT FK_Pago_OrdenDePago
	FOREIGN KEY (K_ORDENDEPAGO) REFERENCES  OrdenDePago (K_ORDENDEPAGO)
;

ALTER TABLE  Paso 
 ADD CONSTRAINT FK_Paso_EmpresaCP
	FOREIGN KEY (K_IDEMPRESA) REFERENCES  EmpresaCP (K_IDEMPRESA)
;

ALTER TABLE  Persona 
 ADD CONSTRAINT FK_Persona_Pais
	FOREIGN KEY (K_PAIS) REFERENCES  Pais (K_PAIS)
;

ALTER TABLE  ProgramacionDiaria 
 ADD CONSTRAINT FK_ProgramacionDiaria_Empleado
	FOREIGN KEY (K_IDENTIFICACION,K_TIPOID) REFERENCES  Empleado (K_IDENTIFICACION,K_TIPOID)
;

ALTER TABLE  ProgramacionDiaria 
 ADD CONSTRAINT FK_ProgramacionDiaria_Puerto
	FOREIGN KEY (K_PUERTOLLEGADA) REFERENCES  Puerto (K_PUERTO)
;

ALTER TABLE  ProgramacionDiaria 
 ADD CONSTRAINT FK_ProgramacionDiaria_Puerto02
	FOREIGN KEY (K_PUERTOSALIDA) REFERENCES  Puerto (K_PUERTO)
;

ALTER TABLE  ProgramacionDiaria 
 ADD CONSTRAINT FK_ProgramacionDiaria_Reserva
	FOREIGN KEY (K_RESERVA) REFERENCES  Reserva (K_RESERVA)
;

ALTER TABLE  Puja 
 ADD CONSTRAINT FK_Puja_Responsable
	FOREIGN KEY (K_IDENTIFICACION,K_TIPOID) REFERENCES  Responsable (K_IDENTIFICACION,K_TIPOID)
;

ALTER TABLE  Puja 
 ADD CONSTRAINT FK_Puja_Subasta
	FOREIGN KEY (K_SUBASTA) REFERENCES  Subasta (K_SUBASTA)
;

ALTER TABLE  Reserva 
 ADD CONSTRAINT FK_Reserva_Buque
	FOREIGN KEY (K_BUQUE) REFERENCES  Buque (K_BUQUE)
;

ALTER TABLE  Reserva 
 ADD CONSTRAINT FK_Reserva_Esclusa
	FOREIGN KEY (K_ESCLUSA) REFERENCES  Esclusa (K_ESCLUSA)
;

ALTER TABLE  Reserva 
 ADD CONSTRAINT FK_Reserva_Responsable
	FOREIGN KEY (K_IDENTIFICACION,K_TIPOID) REFERENCES  Responsable (K_IDENTIFICACION,K_TIPOID)
;

ALTER TABLE  ReservaSubasta 
 ADD CONSTRAINT FK_ReservaSubasta_Reserva
	FOREIGN KEY (K_RESERVA) REFERENCES  Reserva (K_RESERVA)
;

ALTER TABLE  ReservaSubasta 
 ADD CONSTRAINT FK_ReservaSubasta_Subasta
	FOREIGN KEY (K_SUBASTA) REFERENCES  Subasta (K_SUBASTA)
;

ALTER TABLE  Responsable 
 ADD CONSTRAINT FK_RESPONSABLE_OPERADORBARCO
	FOREIGN KEY (K_CRN) REFERENCES  OperadorBarco (K_CRN)
;

ALTER TABLE  Responsable 
 ADD CONSTRAINT FK_Responsable_Persona
	FOREIGN KEY (K_IDENTIFICACION,K_TIPOID) REFERENCES  Persona (K_IDENTIFICACION,K_TIPOID)
;

ALTER TABLE  TarifaCancelacion 
 ADD CONSTRAINT FK_TarifaCancelacion_EmpresaCP
	FOREIGN KEY (K_IDEMPRESA) REFERENCES  EmpresaCP (K_IDEMPRESA)
;

ALTER TABLE  TarifaPeaje 
 ADD CONSTRAINT FK_TarifaPeaje_CategoriaBuque
	FOREIGN KEY (K_CATEGORIA) REFERENCES  CategoriaBuque (K_CATEGORIA)
;

ALTER TABLE  TarifaPeaje 
 ADD CONSTRAINT FK_TarifaPeaje_EmpresaCP
	FOREIGN KEY (K_IDEMPRESA) REFERENCES  EmpresaCP (K_IDEMPRESA)
;

ALTER TABLE  TarifaPeaje 
 ADD CONSTRAINT FK_TarifaPeaje_Esclusa
	FOREIGN KEY (K_ESCLUSA) REFERENCES  Esclusa (K_ESCLUSA)
;

ALTER TABLE  TarifaReserva 
 ADD CONSTRAINT FK_TarifaReserva_EmpresaCP
	FOREIGN KEY (K_IDEMPRESA) REFERENCES  EmpresaCP (K_IDEMPRESA)
;

ALTER TABLE  Transito 
 ADD CONSTRAINT FK_Transito_Esclusa
	FOREIGN KEY (K_ESCLUSA) REFERENCES  Esclusa (K_ESCLUSA)
;

ALTER TABLE  Transito 
 ADD CONSTRAINT FK_Transito_Reserva
	FOREIGN KEY (K_RESERVA) REFERENCES  Reserva (K_RESERVA)
;

ALTER TABLE  Tripulante 
 ADD CONSTRAINT FK_Tripulante_Persona
	FOREIGN KEY (K_IDENTIFICACION,K_TIPOID) REFERENCES  Persona (K_IDENTIFICACION,K_TIPOID)
;
